Left Down Down  "Proceedings of the th" Backspace Backspace 
 "Third International Symposium on Biological Control of Art" 
 "hropods. Christchurch, New Zealandd" Backspace Backspace Backspace 
Backspace Backspace Backspace Backspace Backspace Backspace 
Backspace Backspace DownImage DownImage Down Down  "New Zeal" 
 "and, 8-13 Fr" Backspace  "ebruary 2009." Down  "Mason, P.G" 
 ".; Gillespie, D.R.; Vincent, C." Enter  "United States Dep" 
 "artment of Agriculture, Forest Service, Morgantown, WV, FH" 
 "TET-2008-6" UpImage UpImage Up Up Right Right  "31-Dec-200" 
 "8" Enter  "~" Down Down Down Down Up 