Esc {Ask} {species} 
Menu {Ask} {hosts} 
Menu {Ask} {dist} 
Menu {Ask} {master} Right Example  "1" Down Example  "2" Down 
Example  "3" UpImage Right Example  "3" UpImage Right Example 
 "2!" UpImage Right Example  "1!" DownImage DownImage DownImage 
Up Up Right Check Right Check Right Right Check Down Check Left 
Left Check Left Check Down Check Right Check Right Right Check 
Left Left Left Left Left 
Menu {Scripts} {End-Record} 