SETKEY -47 PLAY "REFLOOK"; press Alt-V 
SETKEY -22 PLAY "REFALTER"; press Alt-U
SETKEY -48 PLAY "HOSCHECK"; press Alt-B; was play "TAXON"
SETKEY -49 PLAY "NEWHOST"; press Alt-N [Alt-M is -50], "Newmemo"
SETKEY -35 PLAY "MOVEHOST"; press Alt-H
SETKEY -36 PLAY "JOURCOPY"; Alt-J
SETKEY -34 PLAY "COPYREF"; Alt-G
;SETKEY -33 PLAY "ADDZR"; press Alt-F
;Keycodes for Toshiba are:
;-47, Alt-V plays NEWHOST
;-35, Alt-H plays "Movehost"
;-22, Alt-U plays Joucop1