h:
dir
pause
cd pdoxdata
cd hymenopt
cd chalcids
c:
copy hknew.* h:
copy language.* h:
copy Tran.* h:
copy hostfam.db h:
copy hostfam.f h:
copy hostfam.f1 h:
copy hostfam.px h:
copy hostfam.val h:
copy hosplant.db h:
copy newhost.db h:
copy master.db h:
copy master.f h:
copy master.f1 h:
copy master.f2 h:
copy master.f3 h:
copy master.f4 h:
copy master.f8 h:
copy master.px h:
copy master.xg1 h:
copy master.xg2 h:
copy master.yg0 h:
copy master.yg1 h:
copy master.yg2 h:
copy famtrib.* h:f
copy genus.db h:
copy genus.mb h:
copy genus.px h:
copy species.db h:
copy species.mb h:
copy species.px h:
copy tstat.db h:
copy tstat.mb h:
copy tstat.px h:
copy hosts.db h:
copy hosts.mb h:
copy hosts.px h:
copy refs.f h:
copy refs.f1 h:
copy refs.px h:
copy dist.db h:
copy dist.mb h:
copy refs.db h:
copy refs.px h:
copy refext.db h:
copy refext.f h:
copy refext.px h:
copy coll.* h:
copy country.* h:
copy ctry-rep.* h:
copy reliable.* h:
copy status.* h:
copy par-rep.* h:
copy distable.* h:
copy counrep2.* h: 
copy hostref2.* h:
copy famref1.* h:
copy famrep2.* h:
copy keyrep.* h:
copy key-rep.* h:
copy authrep.* h:
copy par-rep1.* h:
copy hfamrep2.* h:
copy famrep1.* h:
copy Prfmctry.* h:
copy famrep.* h:
copy lschnoref.* h:
copy hfamrep.* h:
copy hostref.* h:
copy hstnoref.* h:
copy hfamrep3.* h:
copy lstchrep.* h:
copy chdstref.* h:
copy hstnorf1.* h:
copy hostref1.* h:
copy famnames.* h:
copy taxnoref.* h:
copy lstfgref.* h:
copy reftable.* h:
copy relation.* h:
copy taxrep01.* h:
copy Stat-rep.* h:
copy key-rep.* h:
copy ctry-rep.* h:
copy fam-rep.* h:
copy keywords.* h:
copy key-rep.* h:
copy h-fam.* h:
copy p-type.* h:
copy fgnames.* h:
copy Aamain.sc h:
copy distrib.sc h:
copy taxon.sc h:
copy hosfind1.sc h:
copy hosfind2.sc h:
copy authlook.sc h:
copy hosrep1.sc h:
copy hosrep2.sc h:
copy reflook.sc h:
copy sc-cat.sc h:
copy init.sc h:
copy protrec.sc h:
copy valname.* h:
h:
cd\
f:
logout
c:

